import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/app/[locale]/components/Navbar";
import Footer from "@/app/[locale]/components/Footer";
import {ThemeProvider} from "@/app/context/ThemeContext";
import ClientThemeWrapper from "@/app/context/ClientThemeWrapper";
import {routing} from "@/i18n/routing";
import {notFound} from "next/navigation";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import "../../../node_modules/flag-icons/css/flag-icons.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                             params
                                         }: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    // Ensure that the incoming `locale` is valid
    const {locale} = await params;
    if (!routing.locales.includes(locale as any)) {
        notFound();
    }
    {
        const messages = await getMessages();
        return (
            <html lang={locale}>
            <body className={inter.className}>
            <NextIntlClientProvider messages={messages}>
                <ThemeProvider>
                    <ClientThemeWrapper>
                        <div className="ThemedBody">
                            <div className="navbar">
                                <Navbar/>
                            </div>
                            <div className="content">
                                <main>{children}</main>
                            </div>
                            <div className="footer">
                                <Footer/>
                            </div>
                        </div>
                    </ClientThemeWrapper>
                </ThemeProvider>
            </NextIntlClientProvider>
            </body>
            </html>
        );
    }
}